# 전처리

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import h5py

import os

# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # or '3' to suppress most of the logs
# tf.get_logger().setLevel('WARNING')  # Adjust logging level

In [2]:
df = pd.read_csv('C:\\Users\\user\\Desktop\\BigF\\team5\\classify\\combined_product_infos_with_colors_final.csv')
# X = np.load('images64.npy')
# y = np.load('styles64.npy')
# X and y are now numpy arrays containing your data
df

Unnamed: 0.1  Unnamed: 0  \
0                 0           0   
1                 1           1   
2                 2           2   
3                 3           3   
4                 4           7   
...             ...         ...   
23288         23288       47392   
23289         23289       47393   
23290         23290       47395   
23291         23291       47396   
23292         23292       47397   

                                                Category  \
0      ['Home & Kitchen', 'Furniture', 'Living Room F...   
1      ['Home & Kitchen', 'Furniture', 'Living Room F...   
2      ['Home & Kitchen', 'Furniture', 'Living Room F...   
3      ['Home & Kitchen', 'Furniture', 'Living Room F...   
4      ['Home & Kitchen', 'Furniture', 'Living Room F...   
...                                                  ...   
23288  ['Office Products', 'Office Furniture & Lighti...   
23289  ['Home & Kitchen', 'Furniture', 'Home Office F...   
23290  ['Home & Kitchen', 'Furniture', 'Home Office F...   
23291  ['Home & Kitchen', 'Furniture', 'Home Office F...   
23292  ['Home & Kitchen', 'Furniture', 'Home Office F...   

                                                   Title            Price  \
0      HONBAY Modular Sofa Sleeper Sectional Converti...        $1,299.99   
1      CHITA Oversized Modular Sectional Fabric Sofa ...        $1,999.99   
2      HONBAY Modular Sleeper Sofa Bed with Storage S...        $2,599.99   
3      JUMMICO Convertible Sectional Sofa Couch, L-Sh...          $249.97   
4      Devion Furniture Contemporary Reversible Secti...          $426.02   
...                                                  ...              ...   
23288           Martin Furniture Storage Credenza, Brown          $961.93   
23289  MoNiBloom Modern Desk and Chair Set, 95°-125° ...  Price not Found   
23290  Tribesigns 63 Inch Computer Desk with File Dra...          $159.99   
23291  GABRYLLY Ergonomic Mesh Office Chair, High Bac...          $269.50   
23292  Casa Mare 87" Wood Office Furniture Set of 3pc...        $2,199.00   

                                            Product_Info  \
0      {'Brand': 'HONBAY', 'Assembly Required': 'Yes'...   
1      {'Brand': 'CHITA', 'Assembly Required': 'Yes',...   
2      {'Brand': 'HONBAY', 'Seat Depth': '20.5 inches...   
3      {'Brand': 'JUMMICO', 'Assembly Required': 'Yes...   
4      {'Brand': 'Devion Furniture', 'Assembly Requir...   
...                                                  ...   
23288  {'Brand': 'Martin Furniture', 'Color': 'Brown'...   
23289  {'Color': 'Black', 'Brand': 'MoNiBloom', 'Shap...   
23290  {'Brand': 'Tribesigns', 'Product Dimensions': ...   
23291  {'Brand': 'GABRYLLY', 'Color': 'Black', 'Produ...   
23292  {'Color': 'White & Brown', 'Brand': 'Casa Mare...   

                                         Product_Feature  \
0      {'Seating Capacity': '6.00', 'Style': 'Modern'...   
1      {'Seating Capacity': '6', 'Style': 'Modern', '...   
2       {'Seating Capacity': '12.00', 'Style': 'Modern'}   
3      {'Seating Capacity': '3.00', 'Style': 'Modern'...   
4      {'Seating Capacity': '3', 'Style': 'Contempora...   
...                                                  ...   
23288  {'Material': 'Wood', 'Style': 'French', 'Numbe...   
23289    {'Style': 'Modern', 'Assembly Required': 'Yes'}   
23290  {'Shape': 'Rectangular', 'Desk design': 'Compu...   
23291  {'Material': 'Steel, mesh, nylon', 'Item Weigh...   
23292  {'Item Weight': '800 Pounds', 'Style': 'Modern...   

                                            Product_Text  \
0      Modular Sofa: The modular sectional sofa featu...   
1      6-PIECE U-SHAPED MODULAR SOFA WITH LARGER SEAT...   
2      Flexible Combination: Each piece of the modula...   
3      Comfortable Sectional Couch: Made of modern li...   
4      Finish: Dark Gray Material: Polyester Fabric T...   
...                                                  ...   
23288  Product Dimensions: 68W x 30H x 18D Ebony fini...   
23289  Easy Mainte

In [10]:
len(y), len(X), type(y), type(X)

(23343, 23343, numpy.ndarray, numpy.ndarray)

In [11]:
np.unique(y,return_counts=True)

(array(['Classic', 'Contemporary', 'Country', 'Minimalism', 'Modern',
        'Unique', 'Urban'], dtype='<U12'),
 array([ 2668,  1631,  1157,   190, 16642,    70,   985]))

In [12]:
# 모던 줄이기
# 줄이고자 하는 값과 그 개수 설정
value_to_reduce = 'Modern'
desired_count = 2500

# 값의 인덱스 찾기
indices = np.where(y == value_to_reduce)[0]

# 원하는 개수 이상의 인덱스 제거
if len(indices) > desired_count:
    indices_to_remove = indices[desired_count:]
    tempy = np.delete(y, indices_to_remove)
    tempX = np.delete(X, indices_to_remove, axis=0)
np.unique(tempy, return_counts=True)

# 유니크 삭제
indices_to_remove = np.where(tempy == 'Unique')[0]

# 'Modern' 값을 가진 인덱스를 y 배열에서 제거
tempy2 = np.delete(tempy, indices_to_remove)
# 동일한 인덱스를 X 배열에서 제거 (X가 2차원 배열일 경우 axis=0)
rX = np.delete(tempX, indices_to_remove, axis=0)

# 결과 확인
print(np.unique(tempy2, return_counts=True))

(array(['Classic', 'Contemporary', 'Country', 'Minimalism', 'Modern',
       'Urban'], dtype='<U12'), array([2668, 1631, 1157,  190, 2500,  985]))


In [13]:
ry = np.where(tempy2 == 'Minimalism', 'Contemporary', tempy2)

In [14]:
print(np.unique(ry, return_counts=True))
ry.shape

(array(['Classic', 'Contemporary', 'Country', 'Modern', 'Urban'],
      dtype='<U12'), array([2668, 1821, 1157, 2500,  985]))


(9131,)

In [15]:
from sklearn.calibration import LabelEncoder
import joblib

le = LabelEncoder()
ley = le.fit_transform(ry)

# Save the LabelEncoder
joblib.dump(le, 'label_encoder_r.joblib')

['label_encoder_r.joblib']

In [16]:
print(np.unique(ley, return_counts=True))
len(ley), ley.shape

(array([0, 1, 2, 3, 4]), array([2668, 1821, 1157, 2500,  985]))


(9131, (9131,))

# DNN

In [14]:
from tensorflow.keras.utils import to_categorical

# Assuming y contains integer labels
cay = to_categorical(ry, num_classes=5)
cay.shape

(9131, 5)

In [39]:
print(np.unique(ley, return_counts=True))
print(np.unique(ry, return_counts=True))
ley.shape

(array([0, 1, 2, 3, 4]), array([2668, 1821, 1157, 2500,  985]))
(array(['Classic', 'Contemporary', 'Country', 'Modern', 'Urban'],
      dtype='<U12'), array([2668, 1821, 1157, 2500,  985]))


(9131,)

In [40]:
from sklearn.model_selection import train_test_split

# Now proceed with the train_test_split
X_train, X_temp, y_train, y_temp = train_test_split(rX, ry, test_size=0.15, random_state=1, stratify=ry)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=1, stratify=y_temp)

In [41]:
print(X_train.shape, X_val.shape, X_test.shape)
print(y_train.shape, y_val.shape, y_test.shape)

(7761, 64, 64, 3) (685, 64, 64, 3) (685, 64, 64, 3)
(7761,) (685,) (685,)


In [42]:
X_train.shape[1:]

(64, 64, 3)

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Activation, BatchNormalization, Dropout, Conv2D, AvgPool2D, Flatten, LeakyReLU

In [44]:
model_DNN = Sequential([
    Input(X_train.shape[1:]),
    
    Conv2D(filters=32, kernel_size=(4,4), strides=(1,1), padding='same'),
    BatchNormalization(),
    LeakyReLU(alpha=0.01),
    AvgPool2D(pool_size=(4,4)),
    
    Conv2D(filters=16, kernel_size=(4,4), strides=(1,1), padding='same'),
    BatchNormalization(),
    LeakyReLU(alpha=0.01),
    AvgPool2D(pool_size=(4,4)),
    
    Conv2D(filters=8, kernel_size=(4,4), strides=(1,1), padding='same'),
    BatchNormalization(),
    LeakyReLU(alpha=0.01),
    AvgPool2D(pool_size=(4,4)),
    
    Flatten(),
    
    Dense(128),
    BatchNormalization(),
    LeakyReLU(alpha=0.01),
    Dropout(0.2),
    
    Dense(5),
    Activation('softmax')
])

model_DNN.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 64, 64, 32)        1568      
                                                                 
 batch_normalization (Batch  (None, 64, 64, 32)        128       
 Normalization)                                                  
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 64, 64, 32)        0         
                                                                 
 average_pooling2d (Average  (None, 16, 16, 32)        0         
 Pooling2D)                                                      
                                                                 
 conv2d_1 (Conv2D)           (None, 16, 16, 16)        8208      
                                                                 
 batch_normalization_1 (Bat  (None, 16, 16, 16)        6

2024-01-07 15:46:48.812502: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-01-07 15:46:48.843884: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


                                                                 
 average_pooling2d_2 (Avera  (None, 1, 1, 8)           0         
 gePooling2D)                                                    
                                                                 
 flatten (Flatten)           (None, 8)                 0         
                                                                 
 dense (Dense)               (None, 128)               1152      
                                                                 
 batch_normalization_3 (Bat  (None, 128)               512       
 chNormalization)                                                
                                                                 
 leaky_re_lu_3 (LeakyReLU)   (None, 128)               0         
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (

In [45]:
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

early_stopping = EarlyStopping(
                            #    monitor='val_loss',
                               monitor='val_accuracy',
                               patience=15,
                               verbose=1,
                               restore_best_weights=True)

reduce_lr = ReduceLROnPlateau(monitor='val_loss',
                              factor=0.2,
                              patience=15,
                              verbose=1,
                              min_lr=0.001)


In [46]:
# compile the model
model_DNN.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
print('start fitting')
history = model_DNN.fit(
    X_train, y_train,
    epochs=10000000,
    batch_size=32,
    validation_data=(X_val,y_val),
    callbacks=[early_stopping, reduce_lr],
    verbose=1,
)

print('fitting done')

Num GPUs Available:  0
start fitting
Epoch 1/10000000


ValueError: in user code:

    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/losses.py", line 2221, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "/home/hwang/.local/lib/python3.10/site-packages/keras/src/backend.py", line 5573, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 5) are incompatible


In [22]:
y_pred = model_DNN.predict(X_test)
print(y_pred[0])

import numpy as np

y_pred_labels = np.argmax(y_pred, axis=1)
y_pred_labels[:10]



22/22 [==============================] - 0s 9ms/step
[1.7875820e-01 1.1644329e-01 9.1719755e-04 7.0386475e-01 1.6576321e-05]


array([3, 2, 1, 1, 3, 1, 0, 3, 4, 0])

In [23]:
if y_test.ndim > 1:  # Check if y_test is one-hot encoded
    y_test_int_labels = np.argmax(y_test, axis=1)
else:
    y_test_int_labels = y_test  # y_test is already in integer label format

# Now calculate the accuracy
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test_int_labels, y_pred_labels))
print("Confusion Matrix:\n", confusion_matrix(y_test_int_labels, y_pred_labels))
print("Classification Report:\n", classification_report(y_test_int_labels, y_pred_labels))


Accuracy: 0.6934306569343066
Confusion Matrix:
 [[165   6   6   8  15]
 [ 33  62  10  22  10]
 [ 19   4  54   0  10]
 [ 19  21   1 143   3]
 [ 17   0   6   0  51]]
Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.82      0.73       200
           1       0.67      0.45      0.54       137
           2       0.70      0.62      0.66        87
           3       0.83      0.76      0.79       187
           4       0.57      0.69      0.63        74

    accuracy                           0.69       685
   macro avg       0.68      0.67      0.67       685
weighted avg       0.70      0.69      0.69       685



In [24]:
model_DNN.save('./DNN/DNN2.h5')

/home/hwang/.local/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# ML

In [17]:
# Reshape X from (len(X), 64, 64, 3) to (len(X), 1, 12288)
rX_ml = rX.reshape(len(rX),-1)  # -1 tells numpy to infer the dimension

from sklearn.model_selection import train_test_split

# Now proceed with the train_test_split
X_train_ml, X_test_ml, y_train_ml, y_test_ml = train_test_split(rX_ml, ley, test_size=0.1, random_state=1, stratify=ley)

print(X_train_ml.shape, X_test_ml.shape)
print(y_train_ml.shape, y_test_ml.shape)

(8217, 12288) (914, 12288)
(8217,) (914,)


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [23]:
# Random Forest
RFC = RandomForestClassifier()
RFC.fit(X_train_ml, y_train_ml)

# Predictions
y_pred_RFC = RFC.predict(X_test_ml)

# Accuracy
accuracy_RFC = accuracy_score(y_test_ml, y_pred_RFC)
print(f"Accuracy: {accuracy_RFC * 100:.2f} %")

# Precision, Recall, and F1 Score
precision_RFC = precision_score(y_test_ml, y_pred_RFC, average='weighted')
recall_RFC = recall_score(y_test_ml, y_pred_RFC, average='weighted')
f1_RFC = f1_score(y_test_ml, y_pred_RFC, average='weighted')

print(f"Precision: {precision_RFC:.2f} %")
print(f"Recall: {recall_RFC:.2f} %")
print(f"F1 Score: {f1_RFC:.2f} %")

# Confusion Matrix
conf_matrix_RFC = confusion_matrix(y_test_ml, y_pred_RFC)
print("Confusion Matrix:")
print(conf_matrix_RFC)


Accuracy: 81.73%
Precision: 0.83
Recall: 0.82
F1 Score: 0.82
Confusion Matrix:
[[224  11   5  27   0]
 [ 23 139   2  16   2]
 [ 20   8  80   8   0]
 [ 13  13   0 224   0]
 [ 11   4   0   4  80]]


In [24]:
import joblib
# # Load the model from the file
# SVM_model = joblib.load('svm_model.joblib')
print(RFC)
joblib.dump(RFC, './ML/RFC2.joblib')

RandomForestClassifier()


['./ML/RFC2.joblib']

In [20]:
# SVM Classifier
SVM = SVC()

# Random Forest
SVM = RandomForestClassifier()
SVM.fit(X_train_ml, y_train_ml)

# Predictions
y_pred_SVM = SVM.predict(X_test_ml)

# Accuracy
accuracy_SVM = accuracy_score(y_test_ml, y_pred_SVM)
print(f"Accuracy: {accuracy_SVM * 100:.2f} %")

# Precision, Recall, and F1 Score
precision_SVM = precision_score(y_test_ml, y_pred_SVM, average='weighted')
recall_SVM = recall_score(y_test_ml, y_pred_SVM, average='weighted')
f1_SVM = f1_score(y_test_ml, y_pred_SVM, average='weighted')

print(f"Precision: {precision_SVM:.2f} %")
print(f"Recall: {recall_SVM:.2f} %")
print(f"F1 Score: {f1_SVM:.2f} %")

# Confusion Matrix
conf_matrix_SVM = confusion_matrix(y_test_ml, y_pred_SVM)
print("Confusion Matrix:")
print(conf_matrix_SVM)



Accuracy: 82.39%
Precision: 0.83
Recall: 0.82
F1 Score: 0.82
Confusion Matrix:
[[224  14   4  24   1]
 [ 23 141   1  15   2]
 [ 18  10  80   8   0]
 [ 14   9   0 227   0]
 [  6   7   1   4  81]]


In [22]:
# Assuming your SVM model is named as SVM
joblib.dump(SVM, './ML/SVM2.joblib')
print(SVM)
# # Load the model from the file
# SVM_model = joblib.load('svm_model.joblib')

RandomForestClassifier()


In [25]:
# XGBClassifier
XGB= xgb.XGBClassifier()
XGB.fit(X_train_ml, y_train_ml)

# Predictions
y_pred_XGB = XGB.predict(X_test_ml)

# Accuracy
accuracy_XGB = accuracy_score(y_test_ml, y_pred_XGB)
print(f"Accuracy: {accuracy_XGB * 100:.2f}%")

# Precision, Recall, and F1 Score
precision_XGB = precision_score(y_test_ml, y_pred_XGB, average='weighted')
recall_XGB = recall_score(y_test_ml, y_pred_XGB, average='weighted')
f1_XGB = f1_score(y_test_ml, y_pred_XGB, average='weighted')

print(f"Precision: {precision_XGB:.2f}")
print(f"Recall: {recall_XGB:.2f}")
print(f"F1 Score: {f1_XGB:.2f}")

# Confusion Matrix
conf_matrix_XGB = confusion_matrix(y_test_ml, y_pred_XGB)
print("Confusion Matrix:")
print(conf_matrix_XGB)



Accuracy: 81.84%
Precision: 0.82
Recall: 0.82
F1 Score: 0.82
Confusion Matrix:
[[222  16   6  23   0]
 [ 15 144   2  19   2]
 [ 20   7  80   7   2]
 [ 16  10   0 224   0]
 [ 12   7   1   1  78]]


In [26]:
# Assuming your SVM model is named as SVM
joblib.dump(XGB, './ML/XGB2.joblib')
print(XGB)
# # Load the model from the file
# SVM_model = joblib.load('svm_model.joblib')

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)


In [37]:
# Naive Bayes
GNB= GaussianNB()

GNB.fit(X_train_ml, y_train_ml)

# Predictions
y_pred_GNB = GNB.predict(X_test_ml)

# Accuracy
accuracy_GNB = accuracy_score(y_test_ml, y_pred_GNB)
print(f"Accuracy: {accuracy_GNB * 100:.2f}%")

# Precision, Recall, and F1 Score
precision_GNB = precision_score(y_test_ml, y_pred_GNB, average='weighted')
recall_GNB = recall_score(y_test_ml, y_pred_GNB, average='weighted')
f1_GNB = f1_score(y_test_ml, y_pred_GNB, average='weighted')

print(f"Precision: {precision_GNB:.2f}")
print(f"Recall: {recall_GNB:.2f}")
print(f"F1 Score: {f1_GNB:.2f}")

# Confusion Matrix
conf_matrix_GNB = confusion_matrix(y_test_ml, y_pred_GNB)
print("Confusion Matrix:")
print(conf_matrix_GNB)



Accuracy: 36.76%
Precision: 0.40
Recall: 0.37
F1 Score: 0.35
Confusion Matrix:
[[ 55  49  23  74  66]
 [ 22  38   7  64  51]
 [  8  12  19  37  40]
 [ 11  28   6 178  27]
 [  5  12   5  31  46]]


In [ ]:
joblib.dump(GNB, './ML/GNB.joblib')
